'use client';

// Portfolio Insights (Indian tab) — Beta · Alpha · Volatility + a macro-aware AI
// SWOT. Beta/Vol come from the weekly-history regression (live deploy only, like
// the benchmarks); Alpha is portfolio CAGR − Nifty same-dated CAGR; the SWOT is
// generated by /api/insights from the live holdings + risk stats.

const f2 = (n) => (n == null || !isFinite(n) ? '—' : n.toFixed(2));

export default function InsightsCard({ stats, swot, loading }) {
  const s = stats || {};
  const hasReg = s.hasReg;

  // Beta badge — sensitivity to the market
  const betaBadge = s.beta == null ? ['flat', '—']
    : s.beta < 1.05 ? ['low', 'LOW RISK']
    : s.beta < 1.35 ? ['med', 'MED RISK'] : ['high', 'HIGH RISK'];
  // Volatility badge — relative to Nifty
  const volRatio = (hasReg && s.mktVol) ? s.vol / s.mktVol : null;
  const volBadge = volRatio == null ? ['flat', '—']
    : volRatio < 1.2 ? ['low', 'IN LINE']
    : volRatio < 1.6 ? ['med', 'ELEVATED'] : ['high', 'HIGH'];
  // Alpha badge — outperformance
  const alphaBadge = s.alpha == null ? ['flat', '—']
    : s.alpha >= 0 ? ['low', 'OUTPERFORMING'] : ['high', 'LAGGING'];

  const Q = ({ k, label, text }) => (
    <div className={'ins-q ' + k}>
      <div className="qh">◆ {label}</div>
      <div className="qt">{text || '—'}</div>
    </div>
  );

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 }}>
        <div>
          <div className="ctitle">Portfolio Insights</div>
          <div className="sub" style={{ margin: 0 }}>computed from your live holdings</div>
        </div>
        <span className="ins-ai">AI</span>
      </div>

      {/* Beta · Alpha · Volatility */}
      <div className="ins-stats">
        <div className="ins-stat">
          <div className="lbl">Beta (β)</div>
          <div className="v">{hasReg && s.beta != null ? s.beta.toFixed(2) : '—'}</div>
          <div className="sub" style={{ marginTop: 2 }}>1.00 = Nifty</div>
          <span className={'ins-badge ' + betaBadge[0]}>{betaBadge[1]}</span>
        </div>
        <div className="ins-stat">
          <div className="lbl">Alpha (α)</div>
          <div className={'v ' + (s.alpha == null ? '' : s.alpha >= 0 ? 'grn' : 'red')}>
            {s.alpha == null ? '—' : f2(Math.abs(s.alpha))}
          </div>
          <div className="sub" style={{ marginTop: 2 }}>0.00 = Nifty</div>
          <span className={'ins-badge ' + alphaBadge[0]}>{alphaBadge[1]}</span>
        </div>
        <div className="ins-stat">
          <div className="lbl">Volatility</div>
          <div className="v">{hasReg ? <>{s.vol.toFixed(0)}<small>%</small></> : '—'}</div>
          <div className="sub" style={{ marginTop: 2 }}>annualised σ</div>
          <span className={'ins-badge ' + volBadge[0]}>{hasReg && s.mktVol ? `vs Nifty ${s.mktVol.toFixed(0)}%` : volBadge[1]}</span>
        </div>
      </div>

      {/* AI SWOT */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 16 }}>
        <div className="lbl">SWOT</div><span className="ins-ai">AI · macro-aware</span>
      </div>

      {swot ? (
        <>
          {swot.macro ? <div className="ins-macro"><span className="mh">MACRO READ</span>{swot.macro}</div> : null}
          <div className="ins-swot">
            <Q k="s" label="Strengths" text={swot.s} />
            <Q k="w" label="Weaknesses" text={swot.w} />
            <Q k="o" label="Opportunities" text={swot.o} />
            <Q k="t" label="Threats" text={swot.t} />
          </div>
        </>
      ) : loading ? (
        <div className="ins-swot" style={{ marginTop: 12 }}>
          <div className="ins-skel" /><div className="ins-skel" /><div className="ins-skel" /><div className="ins-skel" />
        </div>
      ) : (
        <div className="sub" style={{ marginTop: 12, color: 'var(--txt3)' }}>SWOT appears once AI insights run — hit refresh (needs the insights toggle on).</div>
      )}

      <div className="sub" style={{ marginTop: 12, color: 'var(--txt3)', lineHeight: 1.6 }}>
        From {s.weeks ? s.weeks + '-week' : '~2-year weekly'} returns regressed on Nifty 50: beta is the slope (1.00 = moves with the
        index), alpha the annualised intercept (0.00 = return fully explained by the market), volatility the annualised σ. SWOT is
        AI-generated each refresh — directional, not advice.
      </div>
    </div>
  );
}
