'use client';

// Portfolio Insights (Indian tab) — Beta · Sharpe · Volatility + a macro-aware
// AI SWOT, all from the weekly-history regression (live deploy only, like the
// benchmarks). Sharpe is the risk-adjusted return (not derivable from the
// benchmark table); the SWOT is generated by /api/insights from the live
// holdings + risk stats.

const f2 = (n) => (n == null || !isFinite(n) ? '—' : n.toFixed(2));

export default function InsightsCard({ stats, swot, loading }) {
  const s = stats || {};
  const hasReg = s.hasReg;

  // Beta badge — market sensitivity. ~1 is MARKET-level risk (not "low"); only
  // clearly sub-1 is defensive, clearly >1 is aggressive.
  const betaBadge = s.beta == null ? ['flat', '—']
    : s.beta < 0.9  ? ['low', 'DEFENSIVE']
    : s.beta <= 1.1 ? ['flat', 'MARKET']
    : s.beta < 1.4  ? ['med', 'ELEVATED'] : ['high', 'AGGRESSIVE'];
  // Volatility badge — relative to Nifty
  const volRatio = (hasReg && s.mktVol) ? s.vol / s.mktVol : null;
  const volBadge = volRatio == null ? ['flat', '—']
    : volRatio < 1.2 ? ['low', 'IN LINE']
    : volRatio < 1.6 ? ['med', 'ELEVATED'] : ['high', 'HIGH'];
  // Sharpe badge — risk-adjusted return quality
  const sharpeBadge = s.sharpe == null ? ['flat', '—']
    : s.sharpe >= 1.5 ? ['low', 'STRONG']
    : s.sharpe >= 0.75 ? ['low', 'DECENT']
    : s.sharpe >= 0 ? ['med', 'THIN'] : ['high', 'NEGATIVE'];

  const Q = ({ k, label, text }) => (
    <div className={'ins-q ' + k}>
      <div className="qh">◆ {label}</div>
      <div className="qt">{text || '—'}</div>
    </div>
  );

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 }}>
        <div>
          <div className="ctitle">Portfolio Insights</div>
          <div className="sub" style={{ margin: 0 }}>computed from your live holdings</div>
        </div>
        <span className="ins-ai">AI</span>
      </div>

      {/* Beta · Sharpe · Volatility */}
      <div className="ins-stats">
        <div className="ins-stat">
          <div className="lbl">Beta (β)</div>
          <div className="v">{hasReg && s.beta != null ? s.beta.toFixed(2) : '—'}</div>
          <div className="sub" style={{ marginTop: 2 }}>× Nifty 50 swings</div>
          <span className={'ins-badge ' + betaBadge[0]}>{betaBadge[1]}</span>
        </div>
        <div className="ins-stat">
          <div className="lbl">Sharpe</div>
          <div className={'v ' + (s.sharpe == null ? '' : s.sharpe >= 1 ? 'grn' : s.sharpe < 0 ? 'red' : '')}>
            {s.sharpe == null ? '—' : f2(s.sharpe)}
          </div>
          <div className="sub" style={{ marginTop: 2 }}>return per unit risk</div>
          <span className={'ins-badge ' + sharpeBadge[0]}>{sharpeBadge[1]}</span>
        </div>
        <div className="ins-stat">
          <div className="lbl">Volatility</div>
          <div className="v">{hasReg ? <>{s.vol.toFixed(0)}<small>%</small></> : '—'}</div>
          <div className="sub" style={{ marginTop: 2 }}>annualised σ</div>
          <span className={'ins-badge ' + volBadge[0]}>{hasReg && s.mktVol ? `vs Nifty ${s.mktVol.toFixed(0)}%` : volBadge[1]}</span>
        </div>
      </div>

      {/* AI SWOT */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 16 }}>
        <div className="lbl">SWOT</div><span className="ins-ai">AI · macro-aware</span>
      </div>

      {swot ? (
        <>
          {swot.macro ? <div className="ins-macro"><span className="mh">MACRO READ</span>{swot.macro}</div> : null}
          <div className="ins-swot">
            <Q k="s" label="Strengths" text={swot.s} />
            <Q k="w" label="Weaknesses" text={swot.w} />
            <Q k="o" label="Opportunities" text={swot.o} />
            <Q k="t" label="Threats" text={swot.t} />
          </div>
        </>
      ) : loading ? (
        <div className="ins-swot" style={{ marginTop: 12 }}>
          <div className="ins-skel" /><div className="ins-skel" /><div className="ins-skel" /><div className="ins-skel" />
        </div>
      ) : (
        <div className="sub" style={{ marginTop: 12, color: 'var(--txt3)' }}>SWOT appears once AI insights run — hit refresh (needs the insights toggle on).</div>
      )}

      <div className="sub" style={{ marginTop: 12, color: 'var(--txt3)', lineHeight: 1.6 }}>
        From {s.weeks ? s.weeks + '-week' : 'recent weekly'} returns regressed on Nifty 50: beta is the slope (1.00 = moves with the
        index), volatility the annualised σ. Sharpe is the annualised return above the ~6.5% risk-free rate per unit of that σ
        (&gt;1 good, &gt;2 excellent) — your reward for the bumpiness. SWOT is AI-generated each refresh — directional, not advice.
      </div>
    </div>
  );
}
